spring.application.name=spring-security
server.port=8080

# ===== Base de données PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotheque
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== Logging =====
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.web=info

# ===== Jackson (dates lisibles en JSON) =====
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Europe/Paris

jwt.secret=7147745e0de196b83236fad1a281958a96882930c6ececd68c02c862fe5b0d81
frontend.url=http://localhost:4200